MONGO_URI: 'mongodb://tpos:NyPyM0E5qcZ0oe8osGNakqErzqDVvsCcSHjMkH3lnNY=@172.29.13.16:27017/?authSource=CrawlerDataDB&authMechanism=SCRAM-SHA-1'
MONGO_DB: 'CrawlerDataDB'

HOSTSOCKET: "103.113.81.17"
PORTSOCKET: 9006
URLSOCKET: "http://103.113.81.17:9006"

IP_ADDRESS: '192.168.1.69'
IMAGE_API: 'http://192.168.1.41:8000/api/files/'

